git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --config ~/.config/delta/themes.gitconfig --features lain-lazygit-compact
      # pager: delta --dark --paging=never --config ~/.config/delta/themes.gitconfig --features lain
      # pager: delta --dark --paging=never --config ~/.config/delta/themes.gitconfig --features lain-lazygit
